<a href="https://colab.research.google.com/github/kajalkumari13/Tensors-in-pytorch/blob/main/pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def dy_dx(x):
  return 2*x

In [2]:
dy_dx(3)

6

In [3]:
import math

def dz_dx(x):
  return 2*x*math.cos(x**2)

In [4]:
dz_dx(2)

-2.6145744834544478

In [5]:
import torch

In [6]:
x = torch.tensor(3.0, requires_grad = True)

In [7]:
y = x**2

In [8]:
z = torch.sin(y)

In [9]:
x

tensor(3., requires_grad=True)

In [10]:
y

tensor(9., grad_fn=<PowBackward0>)

In [11]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [12]:
x.grad

In [13]:
import math

def dz_dx(x):
  return 2 * x * math.cos(x**2)

In [14]:
dz_dx(4)

-7.661275842587077

In [15]:
x = torch.tensor(4.0, requires_grad=True)

In [16]:
y=x**2

In [17]:
z = torch.sin(y)

In [18]:
x

tensor(4., requires_grad=True)

In [19]:
y

tensor(16., grad_fn=<PowBackward0>)

In [20]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [21]:
import torch
x = torch.tensor(6.8)
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(1.0)

In [22]:
def binary_cross_entropy_loss(prediction, target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction, epsilon, 1-epsilon)
  return -(target*torch.log(prediction) - (1-target)*torch.log(1-prediction))

In [23]:
z =  w*x+b
y_pred = torch.sigmoid(z)

loss = binary_cross_entropy_loss(y_pred, y)

In [24]:
loss

tensor(-7.8005)

In [25]:
#derivation
dloss_dy_pred = (y_pred -y)/(y_pred*(1-y_pred))
dy_pred_dz = y_pred*(1-y_pred)
dz_dw = x
dz_db = 1

dl_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dl_db = dloss_dy_pred * dy_pred_dz * dz_db

In [27]:
print(f"Manual gradient of loss w.r.t weight (dw): {dl_dw}")
print(f"Manual gradient of loss w.r.t bias (db): {dl_db}")

Manual gradient of loss w.r.t weight (dw): 6.797215461730957
Manual gradient of loss w.r.t bias (db): 0.9995904564857483


In [28]:
x = torch.tensor(6.8)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [29]:
w

tensor(1., requires_grad=True)

In [30]:
b

tensor(0., requires_grad=True)

In [31]:
z = w*x+b
z

tensor(6.8000, grad_fn=<AddBackward0>)

In [32]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9989, grad_fn=<SigmoidBackward0>)

In [33]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(-6.8011, grad_fn=<NegBackward0>)

In [34]:
loss.backward()

In [35]:
print(w.grad)
print(b.grad)

tensor(-6.7924)
tensor(-0.9989)


In [37]:
x = torch.tensor([1.0, 2.0,3.0], requires_grad= True)
x

tensor([1., 2., 3.], requires_grad=True)

In [38]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [39]:
y.backward()

In [43]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [44]:
x.grad.zero_()

tensor([0., 0., 0.])

In [45]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [46]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [47]:
y.backward()

In [48]:
x.grad

tensor(4.)

In [49]:
x.grad.zero_()

tensor(0.)

In [50]:
#Disable Gradient tracking
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [51]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [53]:
y.backward()

In [54]:
x.grad

tensor(4.)

In [55]:
x.requires_grad_(False)
x

tensor(2.)

In [56]:
y = x ** 2
y

tensor(4.)

In [58]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [59]:
z = x.detach()
z

tensor(2.)

In [60]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [61]:
y1 = z**2
y1

tensor(4.)

In [62]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [63]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [64]:
y.backward()