<a href="https://colab.research.google.com/github/kajalkumari13/Tensors-in-pytorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import torch
 print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


In [ ]:
a = torch.empty(3,6)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(3,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
torch.ones(3,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
torch.rand(3,6)

tensor([[0.5475, 0.8696, 0.4429, 0.0893, 0.7105, 0.6824],
        [0.4468, 0.1498, 0.6076, 0.9506, 0.7882, 0.1497],
        [0.7191, 0.4282, 0.7633, 0.6183, 0.1068, 0.5282]])

In [ ]:
torch.manual_seed(42)
torch.rand(3,6)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739]])

In [ ]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


In [ ]:
print("using linspace ->", torch.linspace(0,10,10))

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
print("using eye ->", torch.eye(5))

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
print("using full ->", torch.full((3,3), 5))

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


TENSOR SHAPES


In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[3616445622929465956, 6067528668260871477, 3545804294692942384],
        [6500164550668597550, 7309453675965983778, 8315168162784306286]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])

**TENSOR DATA TYPES**

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

SCALAR OPERATION

In [ ]:
x = torch.rand(2,2)

In [ ]:
x+2

tensor([[2.1053, 2.2695],
        [2.3588, 2.1994]])

In [ ]:
x-2

tensor([[-1.8947, -1.7305],
        [-1.6412, -1.8006]])

In [ ]:
x/3

tensor([[0.0351, 0.0898],
        [0.1196, 0.0665]])

In [ ]:
(x*100)//3

tensor([[ 3.,  8.],
        [11.,  6.]])

In [ ]:
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [ ]:
x**2

tensor([[0.0111, 0.0726],
        [0.1287, 0.0397]])

ELEMENT WISE OPERATION

In [ ]:
a = torch.rand(3,6)
b = torch.rand(3,6)
print(a)
print(b)

tensor([[0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814]])
tensor([[0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913],
        [0.8913, 0.1447, 0.5315, 0.1587, 0.6542, 0.3278]])


In [ ]:
a+b

tensor([[1.3358, 0.5956, 1.7055, 0.2705, 0.8911, 0.8900],
        [0.4541, 1.7192, 1.2219, 1.6111, 1.2128, 0.8336],
        [1.5256, 0.5092, 1.2419, 1.1051, 1.4432, 0.6092]])

In [ ]:
a-b

tensor([[-0.2414, -0.5833,  0.1976, -0.1200,  0.8810,  0.2764],
        [ 0.2212, -0.1013, -0.0661,  0.1969, -0.1035, -0.1490],
        [-0.2570,  0.2197,  0.1789,  0.7877,  0.1349, -0.0464]])

In [ ]:
a*b

tensor([[0.4315, 0.0036, 0.7174, 0.0147, 0.0045, 0.1789],
        [0.0393, 0.7364, 0.3722, 0.6392, 0.3650, 0.1682],
        [0.5654, 0.0527, 0.3776, 0.1502, 0.5162, 0.0922]])

In [ ]:
a/b

tensor([[6.9385e-01, 1.0451e-02, 1.2621e+00, 3.8549e-01, 1.7560e+02, 1.9008e+00],
        [2.8985e+00, 8.8872e-01, 8.9738e-01, 1.2784e+00, 8.4278e-01, 6.9675e-01],
        [7.1170e-01, 2.5176e+00, 1.3367e+00, 5.9624e+00, 1.2061e+00, 8.5847e-01]])

In [ ]:
a**b

tensor([[0.6216, 0.0498, 0.9633, 0.6035, 0.9994, 0.8475],
        [0.8812, 0.8245, 0.7025, 0.9311, 0.6785, 0.5906],
        [0.6665, 0.8641, 0.8338, 0.9913, 0.8564, 0.6599]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

REDUCTION OPERATION

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [ ]:
e

tensor([[0., 1., 3.],
        [0., 1., 1.]])

In [ ]:
torch.sum(e)

tensor(6.)

In [ ]:
torch.sum(e, dim=0)

tensor([0., 2., 4.])

In [ ]:
torch.sum(e, dim=1)

tensor([4., 2.])

In [ ]:
torch.mean(e)

tensor(1.)

In [ ]:
torch.mean(e, dim=0)

tensor([0., 1., 2.])

In [ ]:
torch.mean(e, dim=1)

tensor([1.3333, 0.6667])

In [ ]:
torch.median(e)

tensor(1.)

In [ ]:
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
torch.prod(e)

tensor(0.)

In [ ]:
torch.std(e)

tensor(1.0954)

In [ ]:
torch.var(e)

tensor(1.2000)

In [ ]:
torch.argmax(e)

tensor(2)

In [ ]:
torch.argmin(e)

tensor(0)

MATRIX OPERATIONS

In [ ]:
f = torch.randint(size=(3,6), low=0, high=10)
g = torch.randint(size=(6,3), low=0, high=10)
print(f)
print(g)

tensor([[7, 9, 4, 3, 8, 9],
        [3, 7, 8, 1, 4, 1],
        [6, 3, 2, 0, 9, 8]])
tensor([[5, 3, 7],
        [7, 5, 9],
        [1, 5, 1],
        [9, 1, 4],
        [0, 3, 7],
        [5, 7, 1]])


In [ ]:
torch.matmul(f,g)

tensor([[174, 176, 211],
        [ 86, 104, 125],
        [ 93, 126, 142]])

In [ ]:
vector1 = torch.tensor([3,4])
vector2 = torch.tensor([5,6])
torch.dot(vector1, vector2)

tensor(39)

In [ ]:
torch.transpose(f, 0, 1)

tensor([[7, 3, 6],
        [9, 7, 3],
        [4, 8, 2],
        [3, 1, 0],
        [8, 4, 9],
        [9, 1, 8]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
print(h)

tensor([[5., 7., 5.],
        [8., 5., 4.],
        [1., 1., 0.]])


In [ ]:
torch.det(h)

tensor(23.0000)

In [ ]:
torch.inverse(h)

tensor([[-0.1739,  0.2174,  0.1304],
        [ 0.1739, -0.2174,  0.8696],
        [ 0.1304,  0.0870, -1.3478]])

COMPARISON OPERATIONS

In [ ]:
i = torch.randint(size=(3,6), low=0, high=10)
j = torch.randint(size=(3,6), low=0, high=10)
print(i)
print(j)

tensor([[9, 0, 9, 1, 8, 9],
        [6, 7, 6, 0, 9, 5],
        [2, 9, 1, 7, 8, 6]])
tensor([[0, 6, 8, 6, 8, 0],
        [6, 9, 0, 5, 9, 5],
        [2, 0, 8, 8, 7, 2]])


In [ ]:
i > j

tensor([[ True, False,  True, False, False,  True],
        [False, False,  True, False, False, False],
        [False,  True, False, False,  True,  True]])

In [ ]:
i < j

tensor([[False,  True, False,  True, False, False],
        [False,  True, False,  True, False, False],
        [False, False,  True,  True, False, False]])

In [ ]:
i == j

tensor([[False, False, False, False,  True, False],
        [ True, False, False, False,  True,  True],
        [ True, False, False, False, False, False]])

In [ ]:
i != j

tensor([[ True,  True,  True,  True, False,  True],
        [False,  True,  True,  True, False, False],
        [False,  True,  True,  True,  True,  True]])

In [ ]:
i >= j

tensor([[ True, False,  True, False,  True,  True],
        [ True, False,  True, False,  True,  True],
        [ True,  True, False, False,  True,  True]])

In [ ]:
i <= j

tensor([[False,  True, False,  True,  True, False],
        [ True,  True, False,  True,  True,  True],
        [ True, False,  True,  True, False, False]])

SPECIAL FUNCTIONS

In [ ]:
k = torch.randint(size=(3,6), low=0, high=10, dtype=torch.float32)
print(k)
k

tensor([[2., 6., 8., 2., 7., 6.],
        [3., 0., 3., 6., 0., 3.],
        [7., 3., 8., 9., 8., 2.]])


tensor([[2., 6., 8., 2., 7., 6.],
        [3., 0., 3., 6., 0., 3.],
        [7., 3., 8., 9., 8., 2.]])

In [ ]:
torch.log(k)

tensor([[0.6931, 1.7918, 2.0794, 0.6931, 1.9459, 1.7918],
        [1.0986,   -inf, 1.0986, 1.7918,   -inf, 1.0986],
        [1.9459, 1.0986, 2.0794, 2.1972, 2.0794, 0.6931]])

In [ ]:
torch.exp(k)

tensor([[7.3891e+00, 4.0343e+02, 2.9810e+03, 7.3891e+00, 1.0966e+03, 4.0343e+02],
        [2.0086e+01, 1.0000e+00, 2.0086e+01, 4.0343e+02, 1.0000e+00, 2.0086e+01],
        [1.0966e+03, 2.0086e+01, 2.9810e+03, 8.1031e+03, 2.9810e+03, 7.3891e+00]])

In [ ]:
torch.sqrt(k)

tensor([[1.4142, 2.4495, 2.8284, 1.4142, 2.6458, 2.4495],
        [1.7321, 0.0000, 1.7321, 2.4495, 0.0000, 1.7321],
        [2.6458, 1.7321, 2.8284, 3.0000, 2.8284, 1.4142]])

In [ ]:
torch.sigmoid(k)

tensor([[0.8808, 0.9975, 0.9997, 0.8808, 0.9991, 0.9975],
        [0.9526, 0.5000, 0.9526, 0.9975, 0.5000, 0.9526],
        [0.9991, 0.9526, 0.9997, 0.9999, 0.9997, 0.8808]])

In [ ]:
torch.softmax(k, dim=0)

tensor([[6.5733e-03, 9.5033e-01, 4.9832e-01, 8.6788e-04, 2.6888e-01, 9.3624e-01],
        [1.7868e-02, 2.3556e-03, 3.3577e-03, 4.7385e-02, 2.4518e-04, 4.6613e-02],
        [9.7556e-01, 4.7314e-02, 4.9832e-01, 9.5175e-01, 7.3088e-01, 1.7148e-02]])

In [ ]:
torch.relu(k)

tensor([[2., 6., 8., 2., 7., 6.],
        [3., 0., 3., 6., 0., 3.],
        [7., 3., 8., 9., 8., 2.]])

INPLACE OPERATIONS

In [ ]:
m = torch.rand(3,6)
n = torch.rand(3,6)
print(m)
print(n)

tensor([[0.2234, 0.2469, 0.4761, 0.7792, 0.3722, 0.2147],
        [0.3288, 0.1265, 0.6783, 0.8870, 0.0293, 0.6161],
        [0.7583, 0.5907, 0.3219, 0.7610, 0.7628, 0.6870]])
tensor([[0.4121, 0.3676, 0.5535, 0.4117, 0.3510, 0.8196],
        [0.9297, 0.4505, 0.3881, 0.5073, 0.4701, 0.6202],
        [0.6401, 0.0459, 0.3155, 0.9211, 0.6948, 0.4751]])


In [ ]:
m + n

tensor([[0.6355, 0.6145, 1.0296, 1.1909, 0.7232, 1.0343],
        [1.2585, 0.5770, 1.0664, 1.3943, 0.4994, 1.2363],
        [1.3984, 0.6365, 0.6374, 1.6820, 1.4575, 1.1621]])

In [ ]:
m - n

tensor([[-0.1888, -0.1207, -0.0774,  0.3675,  0.0212, -0.6049],
        [-0.6009, -0.3240,  0.2903,  0.3797, -0.4409, -0.0041],
        [ 0.1182,  0.5448,  0.0065, -0.1601,  0.0680,  0.2118]])

In [ ]:
m.add(n)

tensor([[0.6355, 0.6145, 1.0296, 1.1909, 0.7232, 1.0343],
        [1.2585, 0.5770, 1.0664, 1.3943, 0.4994, 1.2363],
        [1.3984, 0.6365, 0.6374, 1.6820, 1.4575, 1.1621]])

In [ ]:
m

tensor([[0.2234, 0.2469, 0.4761, 0.7792, 0.3722, 0.2147],
        [0.3288, 0.1265, 0.6783, 0.8870, 0.0293, 0.6161],
        [0.7583, 0.5907, 0.3219, 0.7610, 0.7628, 0.6870]])

In [ ]:
n

tensor([[0.4121, 0.3676, 0.5535, 0.4117, 0.3510, 0.8196],
        [0.9297, 0.4505, 0.3881, 0.5073, 0.4701, 0.6202],
        [0.6401, 0.0459, 0.3155, 0.9211, 0.6948, 0.4751]])

In [ ]:
torch.relu(m)

tensor([[0.2234, 0.2469, 0.4761, 0.7792, 0.3722, 0.2147],
        [0.3288, 0.1265, 0.6783, 0.8870, 0.0293, 0.6161],
        [0.7583, 0.5907, 0.3219, 0.7610, 0.7628, 0.6870]])

In [ ]:
m.relu_()

tensor([[0.2234, 0.2469, 0.4761, 0.7792, 0.3722, 0.2147],
        [0.3288, 0.1265, 0.6783, 0.8870, 0.0293, 0.6161],
        [0.7583, 0.5907, 0.3219, 0.7610, 0.7628, 0.6870]])

In [ ]:
m

tensor([[0.2234, 0.2469, 0.4761, 0.7792, 0.3722, 0.2147],
        [0.3288, 0.1265, 0.6783, 0.8870, 0.0293, 0.6161],
        [0.7583, 0.5907, 0.3219, 0.7610, 0.7628, 0.6870]])

In [ ]:
n

tensor([[0.4121, 0.3676, 0.5535, 0.4117, 0.3510, 0.8196],
        [0.9297, 0.4505, 0.3881, 0.5073, 0.4701, 0.6202],
        [0.6401, 0.0459, 0.3155, 0.9211, 0.6948, 0.4751]])

COPYING A TENSOR

In [ ]:
a = torch.rand(3,6)
a

tensor([[0.1985, 0.1941, 0.0521, 0.3370, 0.6689, 0.8188],
        [0.7308, 0.0580, 0.1993, 0.4211, 0.9837, 0.5723],
        [0.3705, 0.7069, 0.3096, 0.1764, 0.8649, 0.2726]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.1985, 0.1941, 0.0521, 0.3370, 0.6689, 0.8188],
        [0.7308, 0.0580, 0.1993, 0.4211, 0.9837, 0.5723],
        [0.3705, 0.7069, 0.3096, 0.1764, 0.8649, 0.2726]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.1941,  0.0521,  0.3370,  0.6689,  0.8188],
        [ 0.7308,  0.0580,  0.1993,  0.4211,  0.9837,  0.5723],
        [ 0.3705,  0.7069,  0.3096,  0.1764,  0.8649,  0.2726]])

In [ ]:
b

tensor([[10.0000,  0.1941,  0.0521,  0.3370,  0.6689,  0.8188],
        [ 0.7308,  0.0580,  0.1993,  0.4211,  0.9837,  0.5723],
        [ 0.3705,  0.7069,  0.3096,  0.1764,  0.8649,  0.2726]])

In [ ]:
id(a)

136493903603920

In [ ]:
id(b)

136493903603920

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[10.0000,  0.1941,  0.0521,  0.3370,  0.6689,  0.8188],
        [ 0.7308,  0.0580,  0.1993,  0.4211,  0.9837,  0.5723],
        [ 0.3705,  0.7069,  0.3096,  0.1764,  0.8649,  0.2726]])

In [ ]:
b

tensor([[10.0000,  0.1941,  0.0521,  0.3370,  0.6689,  0.8188],
        [ 0.7308,  0.0580,  0.1993,  0.4211,  0.9837,  0.5723],
        [ 0.3705,  0.7069,  0.3096,  0.1764,  0.8649,  0.2726]])

In [ ]:
torch.cuda.is_available()

False

In [ ]:
device = torch.device('cuda')

In [ ]:
torch.rand((3,6), device=device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
a = torch.rand((3,6), device=device)

In [ ]:
a = torch.rand((3,6))
a

tensor([[0.3998, 0.0026, 0.8346, 0.8788, 0.6822, 0.1514],
        [0.0065, 0.0939, 0.8729, 0.7401, 0.9208, 0.7619],
        [0.6265, 0.4951, 0.1197, 0.0716, 0.0323, 0.7047]])

In [ ]:
b = a.to(device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
b + 5

RESHAPING TENSORS

In [ ]:
a = torch.ones(4,4)
a

In [ ]:
a.reshape(2,2,2,2)

In [ ]:
a.flatten()

In [ ]:
b = torch.rand(2,3,4)
b

In [ ]:
b.permute(2,1,0).shape

In [ ]:
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

In [ ]:
d = torch.rand(1,20)
d.squeeze(0).shape

NumPy AND PyTorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

In [ ]:
b = a.numpy()

In [ ]:
b

In [ ]:
type(b)

In [ ]:
c = np.array([1,2,3])
c

In [ ]:
 torch.from_numpy(c)